### ISSUE TITLE
UnboundLocalError: local variable 'eval_period' referenced before assignment

### ISSUE THREAD

**Issue by narukamiko** [shmsw25/Channel-LM-Prompting#13]
I run code and found an issue rising:
Traceback (most recent call last):
  File "main.py", line 413, in <module>
    main(logger, args)
  File "main.py", line 77, in main
    acc = run(logger, args.do_train, args.do_zeroshot,
  File "main.py", line 235, in run
    eval_period=eval_period,
UnboundLocalError: local variable 'eval_period' referenced before assignment

Any suggestion?

**Comment by shmsw25** [comment]
Hi @couragelfyang, `eval_period` is defined [here](https://github.com/shmsw25/Channel-LM-Prompting/blob/main/main.py#L171). It is possible you are using a wrong command line (for instance, specifying `--do_zeroshot` and `--do_train` together). Would you tell me what function you intend to run (e.g. do you intend to do training, or zero-shot prompting/in-context learning without training?) and what command line you used?

**Comment by narukamiko** [comment]
My command line I used is:
python3 main.py --task trec --split 'dev' --do_zeroshot --data_dir data --out_dir out --gpt2 gpt2-large --method channel --do_train --batch_size 8 --lr 0.001
I'm going to fine tune the model using a toy dataset (I made with a style like trec) with channel.

**Comment by shmsw25** [comment]
If you are fine-tuning the model, please remove `--do_zeroshot` from the command you are using. The guidelines for tuning can be found [here](https://github.com/shmsw25/Channel-LM-Prompting#prompt-tuning). (Make sure to remove `--prompt_tune`, and use smaller learning rate (e.g. `--learning_rate 1e-05`).)

By the way, if you intend to do standard fine-tuning (not prompt tuning), I recommend using `--method direct` instead of `--method channel`. Direct works better than channel when it comes to standard fine-tuning.

Let me know if you run into any other problem!
