### ISSUE TITLE
running direct model + prompt 

### ISSUE THREAD

**Issue by dorost1234** [shmsw25/Channel-LM-Prompting#6]
Hi
I was wondering why direct model + prompt-tuning is not included in the paper? 
could I run this method with setting prompt_tune=True and model = direct ?
thanks for your help

**Comment by shmsw25** [comment]
Direct prompt tuning is included in the [paper](https://arxiv.org/pdf/2108.04106.pdf). The first paragraph of Section 4.2 mentions prompt tuning can either be direct or channel. The second last column of Table 4 reports direct prompt tuning, and the paragraph below this table (starting with "Comparison when prompt tuning") includes detailed comparisons.

You are right that you can specify `--prompt_tune --method direct` in order to run direct prompt tuning. It's basically the command [here](https://github.com/shmsw25/Channel-LM-Prompting#prompt-tuning) where you use `--method direct`.

**Comment by dorost1234** [comment]
Thanks a lot
