### ISSUE TITLE
datasets are missing

### ISSUE THREAD

**Issue by jackfeinmann5** [shmsw25/Channel-LM-Prompting#8]
Hi
thanks for the codes, I am trying to download the data and subsample them myself for larger Ks, some of the datasets like SST-2, sts-5, mr, cr, trec, subj are missing from the ones you have uploaded, could you kindly let me know from where I can download these? appreciate sharing a download link to the version of these datasets used in this work  if feasible.
thanks

**Comment by shmsw25** [comment]
Hi, as the issue is closed I'm assuming your problem has resolved, but just in case it's helpful: you can download the original, full data from [this link](https://nlp.cs.princeton.edu/projects/lm-bff/datasets.tar) mentioned in [README](https://github.com/shmsw25/Channel-LM-Prompting#download-and-preprocess-data).
