### ISSUE TITLE
initialization from pretrained model's vocabulary

### ISSUE THREAD

**Issue by dorost1234** [shmsw25/Channel-LM-Prompting#9]
Hi
could you tell me how you could compute the top 5000 words for initialization? In the paper you refer to work of lester, I checked that one, apparently they have computed the probability each token appreared during pretraining and took the most common ones, I am not sure how to compute this probability, thanks a lot.

**Comment by shmsw25** [comment]
Hi @dorost1234, thanks for your question. In fact, the vocab is already sorted based on their frequency, so we can just take the first 5000 words in order to take the top 5000 frequent tokens. That initialization is implemented in [these lines](https://github.com/shmsw25/Channel-LM-Prompting/blob/master/model_util.py#L123-L127).
